-- Generated by scripts/generate-supabase-seed.ts.
-- Do not edit manually. Regenerate from src/content/seed/*.ts.
-- The supported application path is a clean database via `npx supabase db reset`.

INSERT INTO public.grades (id, name, display_order)
VALUES
  ('g10', 'الصف العاشر', 10)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  display_order = EXCLUDED.display_order;

INSERT INTO public.semesters (id, grade_id, name, display_order)
VALUES
  ('g10-sem1', 'g10', 'الفصل الدراسي الأول', 1),
  ('g10-sem2', 'g10', 'الفصل الدراسي الثاني', 2)
ON CONFLICT (id) DO UPDATE SET
  grade_id = EXCLUDED.grade_id,
  name = EXCLUDED.name,
  display_order = EXCLUDED.display_order;

INSERT INTO public.subjects (id, grade_id, name, theme_color)
VALUES
  ('g10-physics', 'g10', 'الفيزياء', '#2F6FED')
ON CONFLICT (id) DO UPDATE SET
  grade_id = EXCLUDED.grade_id,
  name = EXCLUDED.name,
  theme_color = EXCLUDED.theme_color;

INSERT INTO public.units (id, subject_id, semester_id, title, display_order)
VALUES
  ('g10-phy-waves-unit', 'g10-physics', 'g10-sem2', 'الموجات', 1)
ON CONFLICT (id) DO UPDATE SET
  subject_id = EXCLUDED.subject_id,
  semester_id = EXCLUDED.semester_id,
  title = EXCLUDED.title,
  display_order = EXCLUDED.display_order;

INSERT INTO public.lessons (id, unit_id, title, display_order, summary, key_concepts, examples, misconceptions, status, source)
VALUES
  ('g10-phy-waves-l1', 'g10-phy-waves-unit', 'مقدمة في الموجات', 1, 'الموجة اضطراب ينتقل ناقلًا الطاقة من مكان إلى آخر دون أن ينتقل معه وسط الانتشار نفسه. تنقسم الموجات بحسب حاجتها إلى وسط مادي: الموجات الميكانيكية (كالصوت وموجات الماء) تحتاج وسطًا لتنتقل، بينما الموجات الكهرومغناطيسية (كالضوء) تنتقل حتى في الفراغ. وتنقسم أيضًا بحسب اتجاه اهتزاز جزيئات الوسط: في الموجة الطولية يهتز الوسط في اتجاه انتشار الموجة، وفي الموجة العرضية يهتز عموديًا على اتجاه انتشارها.', ARRAY['الموجة تنقل الطاقة لا المادة', 'الموجات الميكانيكية تحتاج وسطًا ماديًا', 'الموجات الكهرومغناطيسية تنتقل في الفراغ', 'الموجة الطولية: اهتزاز موازٍ للانتشار', 'الموجة العرضية: اهتزاز عمودي على الانتشار']::text[], ARRAY['الصوت موجة ميكانيكية طولية تحتاج هواءً أو ماءً أو جسمًا صلبًا لتنتقل.', 'ضوء الشمس موجة كهرومغناطيسية تصل إلينا عبر فراغ الفضاء.', 'تموّج حبل مربوط عند هزّه لأعلى وأسفل مثال على الموجة العرضية.']::text[], ARRAY['اعتقاد أن الموجة تنقل المادة نفسها من مكان إلى آخر، والصحيح أنها تنقل الطاقة فقط.', 'اعتقاد أن كل الموجات تحتاج وسطًا، والصحيح أن الموجات الكهرومغناطيسية تنتقل في الفراغ.']::text[], 'draft', 'curriculum_seed'),
  ('g10-phy-waves-l2', 'g10-phy-waves-unit', 'خصائص الموجة', 2, 'توصَف الموجة بعدة مقادير أساسية: الطول الموجي (λ) وهو المسافة بين قمتين متتاليتين، والتردد (f) وهو عدد الموجات المارّة بنقطة في الثانية الواحدة ويُقاس بالهرتز، والسعة وهي أقصى إزاحة عن وضع الاتزان وتدل على طاقة الموجة. وتربط هذه المقادير علاقة مهمة هي v = f λ، حيث v سرعة الموجة. فكلما زاد التردد عند ثبات السرعة قصُر الطول الموجي، والعكس صحيح.', ARRAY['الطول الموجي λ: المسافة بين قمتين متتاليتين', 'التردد f: عدد الموجات في الثانية (هرتز)', 'السعة: أقصى إزاحة عن وضع الاتزان، وتدل على الطاقة', 'العلاقة الأساسية: v = f λ']::text[], ARRAY['عند ضبط محطة راديو على تردد معيّن فأنت تختار موجة بطول موجي محدد.', 'موجة سرعتها 340 م/ث وترددها 170 هرتز طولها الموجي 2 متر (λ = v ÷ f).']::text[], ARRAY['الخلط بين السعة والطول الموجي، والصحيح أن السعة رأسية (طاقة) والطول الموجي أفقي (مسافة).', 'اعتقاد أن زيادة التردد تزيد السرعة دائمًا، والصحيح أن السرعة تحددها خصائص الوسط.']::text[], 'draft', 'curriculum_seed'),
  ('g10-phy-waves-l3', 'g10-phy-waves-unit', 'الموجات الصوتية', 3, 'الصوت موجة ميكانيكية طولية تنتج عن اهتزاز الأجسام، وتحتاج وسطًا ماديًا لتنتقل، لذلك لا ينتقل الصوت في الفراغ. تختلف سرعة الصوت باختلاف الوسط، فهي أكبر في المواد الصلبة منها في السوائل، وأكبر في السوائل منها في الغازات، لأن ترابط الجزيئات أقوى في الصلب. ويوصف الصوت بصفتين: الشدة (العلو) وترتبط بالسعة، وطبقة الصوت (الحدّة) وترتبط بالتردد.', ARRAY['الصوت موجة ميكانيكية طولية', 'الصوت لا ينتقل في الفراغ', 'سرعة الصوت: صلب > سائل > غاز', 'الشدة (العلو) ترتبط بالسعة', 'طبقة الصوت (الحدّة) ترتبط بالتردد']::text[], ARRAY['لا يُسمع انفجار في الفضاء لأن لا وسط مادي ينقل الصوت.', 'ينتقل الصوت في الحديد أسرع من انتقاله في الهواء بكثير.', 'صوت الطفل أعلى حدّة (طبقة) من صوت الرجل لأن تردده أعلى.']::text[], ARRAY['اعتقاد أن الصوت ينتقل في الفراغ مثل الضوء، والصحيح أنه يحتاج وسطًا ماديًا.', 'الخلط بين شدة الصوت وحدّته، والصحيح أن الشدة من السعة والحدّة من التردد.']::text[], 'draft', 'curriculum_seed'),
  ('g10-phy-waves-l4', 'g10-phy-waves-unit', 'سلوك الموجات', 4, 'تُظهر الموجات سلوكيات مميزة عند تفاعلها مع الأوساط أو مع بعضها. فالانعكاس هو ارتداد الموجة عند اصطدامها بحاجز، والانكسار هو تغيّر اتجاه الموجة عند انتقالها بين وسطين مختلفين بسبب تغيّر سرعتها. وعند التقاء موجتين يحدث التداخل: إذا التقت قمة مع قمة تعزّزت الموجة (تداخل بنّاء)، وإذا التقت قمة مع قاع تلاشت أو ضعُفت (تداخل هدّام).', ARRAY['الانعكاس: ارتداد الموجة عن حاجز', 'الانكسار: تغيّر الاتجاه بسبب تغيّر السرعة بين وسطين', 'التداخل البنّاء: قمة + قمة → تعزيز', 'التداخل الهدّام: قمة + قاع → إضعاف']::text[], ARRAY['صدى الصوت في الوادي مثال على انعكاس الموجات الصوتية.', 'ظهور القلم مكسورًا في كأس ماء مثال على انكسار الضوء.', 'تعزّز الصوت في بعض مواضع القاعة وخفوته في مواضع أخرى مثال على التداخل.']::text[], ARRAY['اعتقاد أن الانكسار يعني انكسار الموجة فيزيائيًا، والصحيح أنه تغيّر في اتجاه انتشارها.', 'اعتقاد أن التداخل الهدّام يُفني الطاقة، والصحيح أنها تُعاد توزيعًا لا تُفنى.']::text[], 'draft', 'curriculum_seed')
ON CONFLICT (id) DO UPDATE SET
  unit_id = EXCLUDED.unit_id,
  title = EXCLUDED.title,
  display_order = EXCLUDED.display_order,
  summary = EXCLUDED.summary,
  key_concepts = EXCLUDED.key_concepts,
  examples = EXCLUDED.examples,
  misconceptions = EXCLUDED.misconceptions,
  status = EXCLUDED.status,
  source = EXCLUDED.source;

INSERT INTO public.objectives (id, lesson_id, text)
VALUES
  ('l1-o1', 'g10-phy-waves-l1', 'يميّز الطالب بين الموجة الميكانيكية والموجة الكهرومغناطيسية.'),
  ('l1-o2', 'g10-phy-waves-l1', 'يميّز الطالب بين الموجة الطولية والموجة العرضية.'),
  ('l2-o1', 'g10-phy-waves-l2', 'يُعرّف الطالب الطول الموجي والتردد والسعة.'),
  ('l2-o2', 'g10-phy-waves-l2', 'يطبّق الطالب العلاقة بين السرعة والتردد والطول الموجي (v = f λ).'),
  ('l3-o1', 'g10-phy-waves-l3', 'يفسّر الطالب اعتماد انتقال الصوت على وجود وسط مادي.'),
  ('l3-o2', 'g10-phy-waves-l3', 'يميّز الطالب بين شدة الصوت (العلو) وطبقة الصوت (الحدّة).'),
  ('l4-o1', 'g10-phy-waves-l4', 'يصف الطالب ظاهرتي انعكاس وانكسار الموجات.'),
  ('l4-o2', 'g10-phy-waves-l4', 'يميّز الطالب بين التداخل البنّاء والتداخل الهدّام.')
ON CONFLICT (id) DO UPDATE SET
  lesson_id = EXCLUDED.lesson_id,
  text = EXCLUDED.text;

INSERT INTO public.questions (id, lesson_id, purpose, type, prompt, choices, correct_answer_index, explanation, objective_id, difficulty, status, source)
VALUES
  ('l1-rq1', 'g10-phy-waves-l1', 'review', 'multiple_choice', 'ما الذي تنقله الموجة أساسًا من مكان إلى آخر؟', ARRAY['المادة', 'الطاقة', 'الوسط', 'الجزيئات']::text[], 1, 'الموجة تنقل الطاقة دون أن تنقل معها مادة الوسط نفسه.', 'l1-o1', 'easy', 'draft', 'curriculum_seed'),
  ('l1-rq2', 'g10-phy-waves-l1', 'review', 'multiple_choice', 'أي الموجات التالية تحتاج وسطًا ماديًا لتنتقل؟', ARRAY['الضوء', 'موجات الراديو', 'الصوت', 'الأشعة السينية']::text[], 2, 'الصوت موجة ميكانيكية تحتاج وسطًا ماديًا، بخلاف الموجات الكهرومغناطيسية.', 'l1-o1', 'easy', 'draft', 'curriculum_seed'),
  ('l1-rq3', 'g10-phy-waves-l1', 'review', 'multiple_choice', 'في الموجة الطولية يكون اهتزاز جزيئات الوسط:', ARRAY['عموديًا على اتجاه الانتشار', 'في اتجاه الانتشار نفسه', 'دائريًا حول مركز ثابت', 'بلا اهتزاز']::text[], 1, 'في الموجة الطولية يهتز الوسط موازيًا لاتجاه انتشار الموجة.', 'l1-o2', 'medium', 'draft', 'curriculum_seed'),
  ('l1-rq4', 'g10-phy-waves-l1', 'review', 'multiple_choice', 'أي مما يلي مثال على موجة كهرومغناطيسية؟', ARRAY['موجات الماء', 'الصوت', 'الضوء', 'موجة في حبل']::text[], 2, 'الضوء موجة كهرومغناطيسية تنتقل حتى في الفراغ.', 'l1-o1', 'easy', 'draft', 'curriculum_seed'),
  ('l1-rq5', 'g10-phy-waves-l1', 'review', 'multiple_choice', 'تموّج حبل مربوط عند هزّه لأعلى وأسفل يمثّل موجة:', ARRAY['طولية', 'عرضية', 'كهرومغناطيسية', 'صوتية']::text[], 1, 'اهتزاز الحبل عمودي على اتجاه انتشار الموجة، فهي موجة عرضية.', 'l1-o2', 'medium', 'draft', 'curriculum_seed'),
  ('l1-rq6', 'g10-phy-waves-l1', 'review', 'multiple_choice', 'لماذا تصل أشعة الشمس إلى الأرض عبر الفضاء؟', ARRAY['لأنها موجة ميكانيكية سريعة', 'لأنها موجة كهرومغناطيسية لا تحتاج وسطًا', 'لأن الفضاء مملوء بالهواء', 'لأنها تنقل المادة معها']::text[], 1, 'الضوء موجة كهرومغناطيسية تنتقل في الفراغ دون حاجة إلى وسط مادي.', 'l1-o1', 'medium', 'draft', 'curriculum_seed'),
  ('l2-rq1', 'g10-phy-waves-l2', 'review', 'multiple_choice', 'الطول الموجي هو المسافة بين:', ARRAY['قمة وقاع متتاليين', 'قمتين متتاليتين', 'قاعين بينهما قمتان', 'بداية ونهاية الاهتزاز']::text[], 1, 'الطول الموجي هو المسافة بين قمتين متتاليتين (أو قاعين متتاليين).', 'l2-o1', 'easy', 'draft', 'curriculum_seed'),
  ('l2-rq2', 'g10-phy-waves-l2', 'review', 'multiple_choice', 'وحدة قياس التردد هي:', ARRAY['المتر', 'الثانية', 'الهرتز', 'النيوتن']::text[], 2, 'التردد يُقاس بالهرتز (Hz)، أي عدد الموجات في الثانية.', 'l2-o1', 'easy', 'draft', 'curriculum_seed'),
  ('l2-rq3', 'g10-phy-waves-l2', 'review', 'multiple_choice', 'أي مقدار يدل على طاقة الموجة؟', ARRAY['الطول الموجي', 'التردد', 'السعة', 'السرعة']::text[], 2, 'السعة (أقصى إزاحة عن وضع الاتزان) تدل على طاقة الموجة.', 'l2-o1', 'medium', 'draft', 'curriculum_seed'),
  ('l2-rq4', 'g10-phy-waves-l2', 'review', 'multiple_choice', 'موجة ترددها 50 هرتز وطولها الموجي 4 أمتار، ما سرعتها؟', ARRAY['12.5 م/ث', '54 م/ث', '200 م/ث', '0.08 م/ث']::text[], 2, 'v = f λ = 50 × 4 = 200 م/ث.', 'l2-o2', 'medium', 'draft', 'curriculum_seed'),
  ('l2-rq5', 'g10-phy-waves-l2', 'review', 'multiple_choice', 'عند ثبات سرعة الموجة، إذا زاد ترددها فإن طولها الموجي:', ARRAY['يزداد', 'يقصُر', 'يبقى ثابتًا', 'ينعدم']::text[], 1, 'من العلاقة v = f λ، عند ثبات v تكون f و λ متناسبتين عكسيًا.', 'l2-o2', 'hard', 'draft', 'curriculum_seed'),
  ('l2-rq6', 'g10-phy-waves-l2', 'review', 'multiple_choice', 'موجة سرعتها 340 م/ث وترددها 170 هرتز، ما طولها الموجي؟', ARRAY['2 متر', '0.5 متر', '510 متر', '57800 متر']::text[], 0, 'λ = v ÷ f = 340 ÷ 170 = 2 متر.', 'l2-o2', 'medium', 'draft', 'curriculum_seed'),
  ('l3-rq1', 'g10-phy-waves-l3', 'review', 'multiple_choice', 'الصوت من حيث النوع موجة:', ARRAY['كهرومغناطيسية عرضية', 'ميكانيكية طولية', 'ميكانيكية عرضية', 'كهرومغناطيسية طولية']::text[], 1, 'الصوت موجة ميكانيكية طولية تحتاج وسطًا ماديًا.', 'l3-o1', 'easy', 'draft', 'curriculum_seed'),
  ('l3-rq2', 'g10-phy-waves-l3', 'review', 'multiple_choice', 'لماذا لا يُسمع الصوت في الفضاء الخارجي؟', ARRAY['لأن الصوت ضعيف هناك', 'لعدم وجود وسط مادي ينقله', 'لأن السرعة عالية جدًا', 'بسبب انعدام الجاذبية']::text[], 1, 'الفضاء فراغ لا يحوي وسطًا ماديًا، والصوت يحتاج وسطًا لينتقل.', 'l3-o1', 'easy', 'draft', 'curriculum_seed'),
  ('l3-rq3', 'g10-phy-waves-l3', 'review', 'multiple_choice', 'في أي وسط ينتقل الصوت بأكبر سرعة؟', ARRAY['الهواء', 'الماء', 'الحديد', 'الفراغ']::text[], 2, 'سرعة الصوت أكبر في الصلب لأن ترابط جزيئاته أقوى.', 'l3-o1', 'medium', 'draft', 'curriculum_seed'),
  ('l3-rq4', 'g10-phy-waves-l3', 'review', 'multiple_choice', 'شدة الصوت (علوّه) ترتبط بأي خاصية للموجة؟', ARRAY['التردد', 'السعة', 'الطول الموجي', 'السرعة']::text[], 1, 'شدة الصوت (العلو) ترتبط بسعة الموجة.', 'l3-o2', 'medium', 'draft', 'curriculum_seed'),
  ('l3-rq5', 'g10-phy-waves-l3', 'review', 'multiple_choice', 'طبقة الصوت (حدّته) ترتبط بأي خاصية للموجة؟', ARRAY['السعة', 'التردد', 'الطاقة', 'الشدة']::text[], 1, 'طبقة الصوت (الحدّة) ترتبط بتردد الموجة؛ كلما زاد التردد زادت الحدّة.', 'l3-o2', 'medium', 'draft', 'curriculum_seed'),
  ('l3-rq6', 'g10-phy-waves-l3', 'review', 'multiple_choice', 'صوت طفل أعلى حدّة من صوت رجل، ما السبب؟', ARRAY['سعة صوت الطفل أكبر', 'تردد صوت الطفل أعلى', 'صوت الطفل أشد', 'طول موجة صوت الطفل أكبر']::text[], 1, 'الحدّة (الطبقة) ترتبط بالتردد، وتردد صوت الطفل أعلى.', 'l3-o2', 'hard', 'draft', 'curriculum_seed'),
  ('l4-rq1', 'g10-phy-waves-l4', 'review', 'multiple_choice', 'ارتداد الموجة عند اصطدامها بحاجز يسمى:', ARRAY['الانكسار', 'الانعكاس', 'التداخل', 'الحيود']::text[], 1, 'الانعكاس هو ارتداد الموجة عند اصطدامها بحاجز.', 'l4-o1', 'easy', 'draft', 'curriculum_seed'),
  ('l4-rq2', 'g10-phy-waves-l4', 'review', 'multiple_choice', 'صدى الصوت في الوادي مثال على:', ARRAY['الانكسار', 'الانعكاس', 'التداخل الهدّام', 'السعة']::text[], 1, 'الصدى ناتج عن انعكاس الموجات الصوتية عن حاجز.', 'l4-o1', 'easy', 'draft', 'curriculum_seed'),
  ('l4-rq3', 'g10-phy-waves-l4', 'review', 'multiple_choice', 'تغيّر اتجاه الموجة عند انتقالها بين وسطين مختلفين يسمى:', ARRAY['الانعكاس', 'الانكسار', 'التداخل', 'الاهتزاز']::text[], 1, 'الانكسار هو تغيّر اتجاه الموجة بسبب تغيّر سرعتها بين وسطين.', 'l4-o1', 'medium', 'draft', 'curriculum_seed'),
  ('l4-rq4', 'g10-phy-waves-l4', 'review', 'multiple_choice', 'ظهور القلم مكسورًا داخل كأس ماء مثال على:', ARRAY['الانعكاس', 'الانكسار', 'التداخل البنّاء', 'الصدى']::text[], 1, 'هذا انكسار للضوء عند انتقاله بين الهواء والماء.', 'l4-o1', 'medium', 'draft', 'curriculum_seed'),
  ('l4-rq5', 'g10-phy-waves-l4', 'review', 'multiple_choice', 'عند التقاء قمة موجة مع قمة موجة أخرى يحدث تداخل:', ARRAY['هدّام', 'بنّاء', 'معدوم', 'انكساري']::text[], 1, 'التقاء قمة مع قمة يعزّز الموجة، وهو تداخل بنّاء.', 'l4-o2', 'medium', 'draft', 'curriculum_seed'),
  ('l4-rq6', 'g10-phy-waves-l4', 'review', 'multiple_choice', 'عند التقاء قمة موجة مع قاع موجة أخرى مماثلة يحدث:', ARRAY['تعزيز الموجة', 'إضعاف أو تلاشي الموجة', 'زيادة التردد', 'انعكاس']::text[], 1, 'التقاء قمة مع قاع يُضعف الموجة أو يُلاشيها، وهو تداخل هدّام.', 'l4-o2', 'hard', 'draft', 'curriculum_seed'),
  ('l1-mq1', 'g10-phy-waves-l1', 'mastery', 'multiple_choice', 'العبارة الصحيحة عن الموجات هي:', ARRAY['كل الموجات تحتاج وسطًا ماديًا', 'الموجة تنقل الطاقة لا المادة', 'الموجة الطولية تهتز عموديًا على انتشارها', 'الضوء موجة ميكانيكية']::text[], 1, 'الموجة تنقل الطاقة دون نقل المادة، وهذه سمة أساسية للموجات.', 'l1-o1', 'medium', 'draft', 'curriculum_seed'),
  ('l1-mq2', 'g10-phy-waves-l1', 'mastery', 'multiple_choice', 'أي زوج يمثّل موجة ميكانيكية وموجة كهرومغناطيسية على الترتيب؟', ARRAY['الضوء والصوت', 'الصوت والضوء', 'الضوء وأشعة الراديو', 'موجات الماء والصوت']::text[], 1, 'الصوت ميكانيكي (يحتاج وسطًا)، والضوء كهرومغناطيسي (ينتقل في الفراغ).', 'l1-o1', 'medium', 'draft', 'curriculum_seed'),
  ('l1-mq3', 'g10-phy-waves-l1', 'mastery', 'multiple_choice', 'الفرق الأساسي بين الموجة الطولية والعرضية هو:', ARRAY['سرعة الانتشار', 'اتجاه اهتزاز الوسط بالنسبة للانتشار', 'الحاجة إلى وسط', 'مقدار الطاقة']::text[], 1, 'التمييز بينهما يقوم على اتجاه اهتزاز الوسط بالنسبة لاتجاه الانتشار.', 'l1-o2', 'hard', 'draft', 'curriculum_seed'),
  ('l1-mq4', 'g10-phy-waves-l1', 'mastery', 'multiple_choice', 'أي مما يلي موجة عرضية؟', ARRAY['الصوت في الهواء', 'موجة في حبل مهتز رأسيًا', 'موجة ضغط في نابض', 'موجة صوتية في الماء']::text[], 1, 'اهتزاز الحبل رأسيًا عمودي على انتشار الموجة، فهي عرضية.', 'l1-o2', 'medium', 'draft', 'curriculum_seed'),
  ('l1-mq5', 'g10-phy-waves-l1', 'mastery', 'multiple_choice', 'لو أُفرِغ جرس كهربائي من الهواء داخل وعاء زجاجي، فإن صوته:', ARRAY['يزداد وضوحًا', 'يختفي تدريجيًا', 'لا يتأثر', 'يتحول إلى ضوء']::text[], 1, 'بزوال الهواء يزول الوسط الناقل للصوت، فيختفي الصوت تدريجيًا.', 'l1-o1', 'hard', 'draft', 'curriculum_seed'),
  ('l2-mq1', 'g10-phy-waves-l2', 'mastery', 'multiple_choice', 'موجة ترددها 25 هرتز وطولها الموجي 8 أمتار، سرعتها:', ARRAY['3.1 م/ث', '33 م/ث', '200 م/ث', '0.32 م/ث']::text[], 2, 'v = f λ = 25 × 8 = 200 م/ث.', 'l2-o2', 'medium', 'draft', 'curriculum_seed'),
  ('l2-mq2', 'g10-phy-waves-l2', 'mastery', 'multiple_choice', 'المقدار الذي يدل على طاقة الموجة هو:', ARRAY['التردد', 'الطول الموجي', 'السعة', 'السرعة']::text[], 2, 'السعة تدل على طاقة الموجة.', 'l2-o1', 'medium', 'draft', 'curriculum_seed'),
  ('l2-mq3', 'g10-phy-waves-l2', 'mastery', 'multiple_choice', 'عند ثبوت السرعة، مضاعفة التردد تؤدي إلى أن الطول الموجي:', ARRAY['يتضاعف', 'ينتصف', 'يبقى ثابتًا', 'يتضاعف أربع مرات']::text[], 1, 'λ و f متناسبتان عكسيًا عند ثبات v، فمضاعفة f تنصّف λ.', 'l2-o2', 'hard', 'draft', 'curriculum_seed'),
  ('l2-mq4', 'g10-phy-waves-l2', 'mastery', 'multiple_choice', 'التردد يُعرّف بأنه:', ARRAY['المسافة بين قمتين', 'عدد الموجات المارّة بنقطة في الثانية', 'أقصى إزاحة عن الاتزان', 'سرعة انتقال الموجة']::text[], 1, 'التردد هو عدد الموجات التي تمر بنقطة معيّنة في الثانية الواحدة.', 'l2-o1', 'easy', 'draft', 'curriculum_seed'),
  ('l2-mq5', 'g10-phy-waves-l2', 'mastery', 'multiple_choice', 'موجة سرعتها 300 م/ث وطولها الموجي 1.5 متر، ترددها:', ARRAY['450 هرتز', '200 هرتز', '0.005 هرتز', '301.5 هرتز']::text[], 1, 'f = v ÷ λ = 300 ÷ 1.5 = 200 هرتز.', 'l2-o2', 'medium', 'draft', 'curriculum_seed'),
  ('l3-mq1', 'g10-phy-waves-l3', 'mastery', 'multiple_choice', 'ترتيب الأوساط تصاعديًا حسب سرعة الصوت فيها:', ARRAY['صلب ثم سائل ثم غاز', 'غاز ثم سائل ثم صلب', 'سائل ثم غاز ثم صلب', 'غاز ثم صلب ثم سائل']::text[], 1, 'سرعة الصوت تزداد من الغاز إلى السائل إلى الصلب لقوة الترابط.', 'l3-o1', 'medium', 'draft', 'curriculum_seed'),
  ('l3-mq2', 'g10-phy-waves-l3', 'mastery', 'multiple_choice', 'صوتان لهما الشدة نفسها لكن أحدهما أحدّ، الفرق بينهما في:', ARRAY['السعة', 'التردد', 'الطاقة', 'الوسط']::text[], 1, 'الحدّة ترتبط بالتردد، فالأحدّ أعلى ترددًا مع تساوي الشدة (السعة).', 'l3-o2', 'hard', 'draft', 'curriculum_seed'),
  ('l3-mq3', 'g10-phy-waves-l3', 'mastery', 'multiple_choice', 'أي العبارات صحيحة عن الصوت؟', ARRAY['ينتقل في الفراغ', 'موجة كهرومغناطيسية', 'يحتاج وسطًا ماديًا لينتقل', 'سرعته في الهواء أكبر من سرعته في الحديد']::text[], 2, 'الصوت موجة ميكانيكية تحتاج وسطًا ماديًا لتنتقل.', 'l3-o1', 'easy', 'draft', 'curriculum_seed'),
  ('l3-mq4', 'g10-phy-waves-l3', 'mastery', 'multiple_choice', 'زيادة سعة الموجة الصوتية تؤدي إلى:', ARRAY['صوت أحدّ', 'صوت أعلى شدة', 'صوت أخفض حدّة', 'تغيّر سرعته']::text[], 1, 'الشدة (العلو) ترتبط بالسعة، فزيادتها تزيد شدة الصوت.', 'l3-o2', 'medium', 'draft', 'curriculum_seed'),
  ('l3-mq5', 'g10-phy-waves-l3', 'mastery', 'multiple_choice', 'السبب في أن سرعة الصوت في الصلب أكبر منها في الغاز:', ARRAY['لأن الصلب أبرد', 'لقوة ترابط جزيئات الصلب', 'لأن الغاز أثقل', 'لأن الصوت كهرومغناطيسي في الصلب']::text[], 1, 'قوة ترابط جزيئات الصلب تنقل الاهتزاز أسرع، فتزيد سرعة الصوت.', 'l3-o1', 'hard', 'draft', 'curriculum_seed'),
  ('l4-mq1', 'g10-phy-waves-l4', 'mastery', 'multiple_choice', 'أي الظواهر ينتج عنها تغيّر في اتجاه الموجة بسبب تغيّر سرعتها؟', ARRAY['الانعكاس', 'الانكسار', 'التداخل البنّاء', 'التداخل الهدّام']::text[], 1, 'الانكسار هو تغيّر الاتجاه الناتج عن تغيّر السرعة بين وسطين.', 'l4-o1', 'medium', 'draft', 'curriculum_seed'),
  ('l4-mq2', 'g10-phy-waves-l4', 'mastery', 'multiple_choice', 'التداخل الهدّام يحدث عند التقاء:', ARRAY['قمة مع قمة', 'قاع مع قاع', 'قمة مع قاع', 'موجتين مختلفتي النوع']::text[], 2, 'التقاء قمة مع قاع يُضعف الموجة، وهو التداخل الهدّام.', 'l4-o2', 'medium', 'draft', 'curriculum_seed'),
  ('l4-mq3', 'g10-phy-waves-l4', 'mastery', 'multiple_choice', 'أي مثال يوضّح انعكاس الموجات؟', ARRAY['ظهور القلم مكسورًا في الماء', 'صدى الصوت في الوادي', 'قوس قزح', 'اختلاف سرعة الضوء في الزجاج']::text[], 1, 'الصدى ناتج عن انعكاس الصوت عن حاجز.', 'l4-o1', 'easy', 'draft', 'curriculum_seed'),
  ('l4-mq4', 'g10-phy-waves-l4', 'mastery', 'multiple_choice', 'عند حدوث التداخل الهدّام فإن طاقة الموجتين:', ARRAY['تفنى تمامًا', 'تُعاد توزيعًا ولا تفنى', 'تتضاعف', 'تتحول إلى حرارة فقط']::text[], 1, 'الطاقة تُعاد توزيعًا في الوسط ولا تفنى؛ مبدأ حفظ الطاقة.', 'l4-o2', 'hard', 'draft', 'curriculum_seed'),
  ('l4-mq5', 'g10-phy-waves-l4', 'mastery', 'multiple_choice', 'ظهور مواضع صوت قوية وأخرى خافتة في قاعة يُفسَّر بـ:', ARRAY['الانكسار وحده', 'التداخل بين الموجات', 'الانعكاس وحده', 'تغيّر التردد']::text[], 1, 'تعاقب المواضع القوية والخافتة ناتج عن التداخل البنّاء والهدّام.', 'l4-o2', 'hard', 'draft', 'curriculum_seed')
ON CONFLICT (id) DO UPDATE SET
  lesson_id = EXCLUDED.lesson_id,
  purpose = EXCLUDED.purpose,
  type = EXCLUDED.type,
  prompt = EXCLUDED.prompt,
  choices = EXCLUDED.choices,
  correct_answer_index = EXCLUDED.correct_answer_index,
  explanation = EXCLUDED.explanation,
  objective_id = EXCLUDED.objective_id,
  difficulty = EXCLUDED.difficulty,
  status = EXCLUDED.status,
  source = EXCLUDED.source;

INSERT INTO public.games (id, lesson_id, type, title, instructions, items, status, source)
VALUES
  ('l1-game', 'g10-phy-waves-l1', 'matching', 'طابِق نوع الموجة مع مثالها', 'صِل كل نوع من الموجات بالمثال المناسب له.', '[{"left":"موجة ميكانيكية طولية","right":"الصوت"},{"left":"موجة كهرومغناطيسية","right":"الضوء"},{"left":"موجة عرضية","right":"اهتزاز حبل رأسيًا"},{"left":"موجة تنتقل في الفراغ","right":"أشعة الشمس"}]'::jsonb, 'draft', 'curriculum_seed'),
  ('l2-game', 'g10-phy-waves-l2', 'matching', 'طابِق المصطلح مع تعريفه', 'صِل كل مصطلح موجيّ بتعريفه الصحيح.', '[{"left":"الطول الموجي","right":"المسافة بين قمتين متتاليتين"},{"left":"التردد","right":"عدد الموجات في الثانية"},{"left":"السعة","right":"أقصى إزاحة عن وضع الاتزان"},{"left":"v = f λ","right":"العلاقة بين السرعة والتردد والطول الموجي"}]'::jsonb, 'draft', 'curriculum_seed'),
  ('l3-game', 'g10-phy-waves-l3', 'matching', 'طابِق الوسط مع سرعة الصوت النسبية فيه', 'رتّب العلاقة بين وسط الانتقال وسرعة الصوت وصفاته.', '[{"left":"الحديد (صلب)","right":"أكبر سرعة للصوت"},{"left":"الماء (سائل)","right":"سرعة متوسطة للصوت"},{"left":"الهواء (غاز)","right":"أقل سرعة للصوت"},{"left":"الفراغ","right":"لا ينتقل فيه الصوت"}]'::jsonb, 'draft', 'curriculum_seed'),
  ('l4-game', 'g10-phy-waves-l4', 'matching', 'طابِق الظاهرة مع مثالها الحياتي', 'صِل كل سلوك موجيّ بالمثال الذي يوضّحه.', '[{"left":"الانعكاس","right":"صدى الصوت في الوادي"},{"left":"الانكسار","right":"ظهور القلم مكسورًا في الماء"},{"left":"التداخل البنّاء","right":"تعزّز الصوت في موضع من القاعة"},{"left":"التداخل الهدّام","right":"خفوت الصوت في موضع من القاعة"}]'::jsonb, 'draft', 'curriculum_seed')
ON CONFLICT (id) DO UPDATE SET
  lesson_id = EXCLUDED.lesson_id,
  type = EXCLUDED.type,
  title = EXCLUDED.title,
  instructions = EXCLUDED.instructions,
  items = EXCLUDED.items,
  status = EXCLUDED.status,
  source = EXCLUDED.source;

INSERT INTO public.experiments (id, lesson_id, title, objective, tools, steps, safety_notes, safety_level, observation_prompt, conclusion_prompt, home_alternative, status, source)
VALUES
  ('l1-exp', 'g10-phy-waves-l1', 'تكوين موجة طولية وأخرى عرضية', 'التمييز عمليًا بين الموجة الطولية والعرضية.', ARRAY['حبل مرن أو نابض لعبة (سلينكي)', 'سطح مستوٍ']::text[], ARRAY['ثبّت أحد طرفي الحبل واجعل الطرف الآخر بيدك.', 'حرّك يدك لأعلى وأسفل لتكوين موجة عرضية ولاحظ شكلها.', 'ادفع الحبل واسحبه في اتجاه امتداده لتكوين موجة طولية ولاحظ مناطق التضاغط والتخلخل.', 'قارن اتجاه اهتزاز يدك مع اتجاه انتشار الموجة في الحالتين.']::text[], ARRAY['تجنّب شدّ الحبل بقوة قرب الوجه أو العينين.']::text[], 'safe_home', 'في أي الحالتين كان اهتزاز يدك موازيًا لاتجاه انتشار الموجة؟', 'استنتج الفرق الأساسي بين الموجة الطولية والعرضية من حيث اتجاه الاهتزاز.', 'يمكن استخدام حبل قفز عادي بدل النابض.', 'draft', 'curriculum_seed'),
  ('l2-exp', 'g10-phy-waves-l2', 'تقدير التردد من عدّ الموجات', 'ربط التردد بعدد الموجات المتكوّنة في زمن محدد.', ARRAY['حبل مرن', 'ساعة توقيت (هاتف)']::text[], ARRAY['ثبّت طرف الحبل وحرّك الطرف الآخر بانتظام لتكوين موجات متتابعة.', 'اطلب من زميل ضبط مؤقّت لعشر ثوانٍ.', 'عُدّ عدد الموجات الكاملة المارّة خلال العشر ثوانٍ.', 'احسب التردد بقسمة عدد الموجات على الزمن بالثواني.']::text[], ARRAY['احرص على مساحة كافية خالية من العوائق حول الحبل.']::text[], 'safe_home', 'كم موجة كاملة عددتها خلال العشر ثوانٍ؟', 'كيف يتغيّر التردد إذا حرّكت يدك أسرع مع ثبات الزمن؟', NULL, 'draft', 'curriculum_seed'),
  ('l3-exp', 'g10-phy-waves-l3', 'هاتف الكوبين والخيط', 'توضيح انتقال الصوت عبر وسط صلب مقارنة بالهواء.', ARRAY['كوبان ورقيان أو بلاستيكيان', 'خيط طويل (3–5 أمتار)', 'مسمار صغير لعمل ثقب']::text[], ARRAY['اثقب قاع كل كوب ثقبًا صغيرًا ومرّر الخيط خلاله واعقده من الداخل.', 'ابتعد مع زميل حتى يشتدّ الخيط بينكما.', 'تحدّث في كوبك بينما يضع زميلك كوبه على أذنه ويستمع.', 'كرّر التجربة مع إرخاء الخيط ولاحظ الفرق في وضوح الصوت.']::text[], ARRAY['احذر من شدّ الخيط المفاجئ قرب الوجه.']::text[], 'safe_home', 'متى كان الصوت أوضح: عند شدّ الخيط أم عند إرخائه؟', 'استنتج لماذا ينقل الخيط المشدود الصوت بوضوح أكبر.', 'الاستماع إلى دقّات الطاولة بوضع الأذن عليها مقارنة بسماعها عبر الهواء.', 'draft', 'curriculum_seed'),
  ('l4-exp', 'g10-phy-waves-l4', 'انكسار الضوء الظاهري', 'ملاحظة انكسار الضوء عند انتقاله بين الهواء والماء.', ARRAY['كأس شفاف', 'ماء', 'قلم رصاص']::text[], ARRAY['املأ الكأس بالماء حتى منتصفه.', 'ضع القلم مائلًا داخل الكأس بحيث يبرز جزء منه فوق سطح الماء.', 'انظر إلى القلم من جانب الكأس.', 'لاحظ موضع القلم عند سطح الماء وقارن الجزء المغمور بالجزء البارز.']::text[], ARRAY['احرص على عدم انسكاب الماء على أجهزة كهربائية.']::text[], 'safe_home', 'كيف بدا القلم عند سطح الماء؟', 'استنتج سبب ظهور القلم مكسورًا بربط ذلك بتغيّر سرعة الضوء بين الوسطين.', 'وضع قطعة نقود في وعاء وملؤه بالماء تدريجيًا وملاحظة تغيّر موضعها الظاهري.', 'draft', 'curriculum_seed')
ON CONFLICT (id) DO UPDATE SET
  lesson_id = EXCLUDED.lesson_id,
  title = EXCLUDED.title,
  objective = EXCLUDED.objective,
  tools = EXCLUDED.tools,
  steps = EXCLUDED.steps,
  safety_notes = EXCLUDED.safety_notes,
  safety_level = EXCLUDED.safety_level,
  observation_prompt = EXCLUDED.observation_prompt,
  conclusion_prompt = EXCLUDED.conclusion_prompt,
  home_alternative = EXCLUDED.home_alternative,
  status = EXCLUDED.status,
  source = EXCLUDED.source;

INSERT INTO public.experiment_objectives (experiment_id, objective_id, lesson_id, position)
VALUES
  ('l1-exp', 'l1-o2', 'g10-phy-waves-l1', 0),
  ('l2-exp', 'l2-o1', 'g10-phy-waves-l2', 0),
  ('l3-exp', 'l3-o1', 'g10-phy-waves-l3', 0),
  ('l4-exp', 'l4-o1', 'g10-phy-waves-l4', 0)
ON CONFLICT (experiment_id, objective_id) DO UPDATE SET
  lesson_id = EXCLUDED.lesson_id,
  position = EXCLUDED.position;

INSERT INTO public.game_objectives (game_id, objective_id, position)
VALUES
  ('l1-game', 'l1-o1', 0),
  ('l1-game', 'l1-o2', 1),
  ('l2-game', 'l2-o1', 0),
  ('l2-game', 'l2-o2', 1),
  ('l3-game', 'l3-o1', 0),
  ('l4-game', 'l4-o2', 0),
  ('l4-game', 'l4-o1', 1)
ON CONFLICT (game_id, objective_id) DO UPDATE SET
  position = EXCLUDED.position;

